on:
  push:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v2
      - name: Install mustache (to update the date)
        run: apk add ruby && gem install mustache
      - name: creates output
        run: sh ./build.sh
      - name: Determine destination repository (non-secret only)
        id: set-destination
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "username=Chasyuss" >> $GITHUB_OUTPUT
            echo "repo=STARLIGHT_FE" >> $GITHUB_OUTPUT
            echo "branch=main" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref }}" = "refs/heads/develop" ]; then
            echo "username=parknari02" >> $GITHUB_OUTPUT
            echo "repo=STARLIGHT_FE" >> $GITHUB_OUTPUT
            echo "branch=develop" >> $GITHUB_OUTPUT
          fi

      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ github.ref == 'refs/heads/main' && secrets.AUTO_ACTIONS || secrets.DEVELOP_ACTIONS }}
        with:
          source-directory: "output"
          destination-github-username: ${{ steps.set-destination.outputs.username }}
          destination-repository-name: ${{ steps.set-destination.outputs.repo }}
          user-email: ${{ github.ref == 'refs/heads/main' && secrets.EMAIL || secrets.DEVELOP_EMAIL }}
          commit-message: ${{ github.event.commits[0].message }}
          target-branch: ${{ steps.set-destination.outputs.branch }}

      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
